Repository usealto/trainx-front, pull requests merged in 2023-07, with the labels that each got.

#65 [LEAD][TEAM] Invite btn not aligned
  src/app/modules/lead-team/components/lead-team/lead-team.component.html
Labels: bug

#67 💄Make “Statistiques” title align with the other pages titles
  src/app/modules/statistics/components/statistics/statistics.component.html
Labels: bug

#72 🐛 Fix: Need to refresh the page to display the newly created team
  src/app/modules/lead-team/components/lead-team/lead-team.component.ts
  src/app/modules/lead-team/components/team-form/team-form.component.ts
Labels: bug

#75 💄 [L/Homepage] UI fix on progression badge
  src/app/modules/shared/components/progression-badge/progression-badge.component.html
Labels: bug

#73 ✨ Tags table updates
  package-lock.json
  package.json
  src/app/I18n/FR.ts
  src/app/modules/programs/components/programs/programs.component.html
  src/app/modules/programs/components/programs/programs.component.ts
  src/app/modules/programs/models/tag.model.ts
  src/app/modules/programs/services/tags-rest.service.ts
  src/app/modules/programs/services/tags-service.service.ts
  src/app/modules/shared/components/tag-delete-modal/tag-delete-modal.component.cy.ts
  src/app/modules/shared/components/tag-delete-modal/tag-delete-modal.component.html
  src/app/modules/shared/components/tag-delete-modal/tag-delete-modal.component.scss
  src/app/modules/shared/components/tag-delete-modal/tag-delete-modal.component.ts
  src/app/modules/shared/services/scores.service.ts
  src/app/modules/shared/shared.module.ts
Labels: enhancement

#103 Storybook init
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/tsconfig.json
  .storybook/typings.d.ts
  angular.json
  package-lock.json
  package.json
  src/app/layout/not-found/not-found.component.stories.ts
  src/app/modules/shared/components/button-group/button-group.component.stories.ts
  src/stories/.eslintrc.json
  src/stories/Configure.mdx
Labels: documentation

#108 removing unused file
  src/app/modules/programs/models/averageCompletion.model.ts
Labels: documentation

#106 🐛 Refresh tags and questions caches based on some events
  src/app/modules/programs/components/programs/programs.component.ts
Labels: bug
