Repository usealto/trainx-front, pull requests merged in 2023-08, with the labels that each got.

#112 [documentation] new shared component : colored pill
  src/app/modules/shared/components/colored-pill/colored-pill.component.stories.ts
Labels: documentation

#119 💄 [Lead] User Form for Roles and Teams
  src/app/I18n/FR.ts
  src/app/modules/lead-team/components/user-edit-form/user-edit-form.component.html
  src/app/modules/lead-team/components/user-edit-form/user-edit-form.component.scss
  src/app/modules/lead-team/components/user-edit-form/user-edit-form.component.ts
  src/app/styles/_bootstrap-override.scss
Labels: enhancement

#121 Storybook echart
  src/app/modules/charts/chart-basicline/chart-basicline.component.html
  src/app/modules/charts/chart-basicline/chart-basicline.component.scss
  src/app/modules/charts/chart-basicline/chart-basicline.component.stories.ts
  src/app/modules/charts/chart-basicline/chart-basicline.component.ts
  src/app/modules/charts/charts.module.ts
  src/stories/Configure.mdx
Labels: documentation

#122 💄 Redesign integrations page
  src/app/I18n/FR.ts
  src/app/modules/settings/components/settings-integrations/settings-integrations.component.html
  src/app/modules/settings/components/settings-integrations/settings-integrations.component.scss
  src/app/modules/settings/components/settings/settings.component.html
  src/app/modules/shared/components/icon-badge/icon-badge.component.scss
  src/app/modules/shared/components/icon-badge/icon-badge.component.ts
  src/assets/img/teams-logo.svg
Labels: enhancement

#123 updating storybook README
  src/app/modules/charts/chart-basicline/chart-basicline.component.stories.ts
  src/stories/Configure.mdx
Labels: documentation

#124 🔨 Fix filterByScore function
  src/app/modules/shared/services/scores.service.ts
Labels: bug

#135 [L/Home] Remove redirection on “question ”suggeree”
  src/app/modules/lead-home/components/lead-home/lead-home.component.html
Labels: bug

#134 [L/Profile] first/lastName should be required
  src/app/modules/profile/components/profile-account/profile-account.component.html
  src/app/modules/profile/components/profile-account/profile-account.component.ts
Labels: bug

#147 Make "score" filter work
  src/app/modules/programs/components/programs/programs.component.html
  src/app/modules/programs/components/programs/programs.component.ts
Labels: bug

#154 🔨🔨 Some fixes due to tag form review
  src/app/I18n/FR.ts
  src/app/modules/programs/components/tags/tag-form/tag-form.component.html
  src/app/modules/programs/components/tags/tag-form/tag-form.component.ts
Labels: bug

#126 ✨ Create storybook components
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/launch.json
  .vscode/tasks.json
  angular.json
  package-lock.json
  package.json
  src/app/modules/shared/components/button-group/button-group.component.stories.ts
  src/app/modules/shared/components/colored-pill/colored-pill.component.stories.ts
  src/app/modules/shared/components/delete-modal/delete-modal.component.stories.ts
  src/app/modules/shared/components/dropdown-filter/dropdown-filter.component.html
  src/app/modules/shared/components/dropdown-filter/dropdown-filter.component.stories.ts
  src/app/modules/shared/components/dropdown-filter/dropdown-filter.component.ts
  src/app/modules/shared/components/img-badge-list/img-badge-list.component.stories.ts
  src/app/modules/shared/components/img-badge/img-badge.component.stories.ts
  src/app/modules/shared/components/pagination/pagination.component.stories.ts
  src/app/modules/shared/components/period-filter/period-filter.component.stories.ts
  src/app/modules/shared/components/profile-card/profile-card.component.stories.ts
  src/app/modules/shared/components/program-card-list/program-card-list.component.stories.ts
  src/app/modules/shared/components/program-card/program-card.component.stories.ts
  src/app/modules/shared/components/progression-badge/progression-badge.component.stories.ts
  src/app/modules/shared/components/progression-filter/progression-filter.component.stories.ts
  src/app/modules/shared/components/question-delete-modal/question-delete-modal.component.stories.ts
  src/app/modules/shared/components/score-filter/score-filter.component.stories.ts
  src/app/modules/shared/components/search/search.component.stories.ts
  src/app/modules/shared/components/status-pill/status-pill.component.stories.ts
  src/app/modules/shared/components/tabs/tabs.component.stories.ts
  src/app/modules/shared/components/text-counter/text-counter.component.stories.ts
  src/app/modules/shared/components/time-picker/time-picker.component.stories.ts
  src/app/modules/shared/components/training-card/training-card.component.stories.ts
  src/app/modules/shared/shared.module.ts
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  tsconfig.app.json
  tsconfig.doc.json
Labels: enhancement

#157 ✅ 🔨 V3.2 lead test updates
  cypress/e2e/lead-team/team-edit.cy.ts
  cypress/e2e/lead-team/team-filters.cy.ts
  cypress/e2e/lead-team/team.cy.ts
Labels: enhancement
